// Code generated by ent, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/abombard/goserver/ent/runtime.go

const (
	Version = "v0.11.11-0.20230313165712-acc4c5aac6c0"          // Version of ent codegen.
	Sum     = "h1:ECmMOhFTjfB0okdge4xHX9kJ7/y0I0XmDdfiOoqwof0=" // Sum of ent codegen.
)
